# Files distributed to students (.ok & tests/ handled automatically)
fa20/vitamin/vitamin10.d: $(MATERIALS_DST)/fa20/vitamin/vitamin10/groups_yelp_data.png
fa20/vitamin/vitamin10.d: $(MATERIALS_DST)/fa20/vitamin/vitamin10/feedback.py
fa20/vitamin/vitamin10.d: $(MATERIALS_DST)/fa20/vitamin/vitamin10/group_yelp_data.csv