# Files distributed to students (.ok & tests/ handled automatically)
fa20/hw/hw09.d: $(MATERIALS_DST)/fa20/hw/hw09/waiting_times.csv
fa20/hw/hw09.d: $(MATERIALS_DST)/fa20/hw/hw09/smallrepvarhist.png
fa20/hw/hw09.d: $(MATERIALS_DST)/fa20/hw/hw09/reviews.csv
fa20/hw/hw09.d: $(MATERIALS_DST)/fa20/hw/hw09/more_reviews.csv
fa20/hw/hw09.d: $(MATERIALS_DST)/fa20/hw/hw09/population_waiting_times.csv
fa20/hw/hw09.d: $(MATERIALS_DST)/fa20/hw/hw09/one_sample.csv