# Files distributed to students (.ok & tests/ handled automatically)
fa20/vitamin/vitamin12.d: $(MATERIALS_DST)/fa20/vitamin/vitamin12/tbl_examples.png
fa20/vitamin/vitamin12.d: $(MATERIALS_DST)/fa20/vitamin/vitamin12/feedback.py