# Files distributed to students (.ok & tests/ handled automatically)
fa20/project/project3.d: $(MATERIALS_DST)/fa20/project/project3/movies.csv
fa20/project/project3.d: $(MATERIALS_DST)/fa20/project/project3/proj3_test_set.csv
fa20/project/project3.d: $(MATERIALS_DST)/fa20/project/project3/stem.csv
fa20/project/project3.d: $(MATERIALS_DST)/fa20/project/project3/word_plot.png