# Files distributed to students (.ok & tests/ handled automatically)
fa20/vitamin/vitamin18.d: $(MATERIALS_DST)/fa20/vitamin/vitamin18/decisions_pvalue.png
fa20/vitamin/vitamin18.d: $(MATERIALS_DST)/fa20/vitamin/vitamin18/feedback.py