# Files distributed to students (.ok & tests/ handled automatically)
fa20/vitamin/vitamin33.d: $(MATERIALS_DST)/fa20/vitamin/vitamin33/residual_question.png
fa20/vitamin/vitamin33.d: $(MATERIALS_DST)/fa20/vitamin/vitamin33/feedback.py