# Files distributed to students (.ok & tests/ handled automatically)
fa20/hw/hw03.d: $(MATERIALS_DST)/fa20/hw/hw03/unemployment.csv
fa20/hw/hw03.d: $(MATERIALS_DST)/fa20/hw/hw03/nst-est2016-alldata.csv
fa20/hw/hw03.d: $(MATERIALS_DST)/fa20/hw/hw03/scatter.png
fa20/hw/hw03.d: $(MATERIALS_DST)/fa20/hw/hw03/var1.png
fa20/hw/hw03.d: $(MATERIALS_DST)/fa20/hw/hw03/var2.png
fa20/hw/hw03.d: $(MATERIALS_DST)/fa20/hw/hw03/var3.png
fa20/hw/hw03.d: $(MATERIALS_DST)/fa20/hw/hw03/boston.csv
fa20/hw/hw03.d: $(MATERIALS_DST)/fa20/hw/hw03/manila.csv