# Files distributed to students (.ok & tests/ handled automatically)
fa20/lab/lab02.d: $(MATERIALS_DST)/fa20/lab/lab02/world_population.csv
fa20/lab/lab02.d: $(MATERIALS_DST)/fa20/lab/lab02/imdb.csv
fa20/lab/lab02.d: $(MATERIALS_DST)/fa20/lab/lab02/farmers_markets.csv
fa20/lab/lab02.d: $(MATERIALS_DST)/fa20/lab/lab02/statement.png