# Files distributed to students (.ok & tests/ handled automatically)
fa20/hw/hw02.d: $(MATERIALS_DST)/fa20/hw/hw02/president_births.csv
fa20/hw/hw02.d: $(MATERIALS_DST)/fa20/hw/hw02/temperatures.csv
fa20/hw/hw02.d: $(MATERIALS_DST)/fa20/hw/hw02/world_population.csv
fa20/hw/hw02.d: $(MATERIALS_DST)/fa20/hw/hw02/array_diff.png
fa20/hw/hw02.d: $(MATERIALS_DST)/fa20/hw/hw02/array_cumsum.png
fa20/hw/hw02.d: $(MATERIALS_DST)/fa20/hw/hw02/old_faithful.csv
fa20/hw/hw02.d: $(MATERIALS_DST)/fa20/hw/hw02/inventory.csv
fa20/hw/hw02.d: $(MATERIALS_DST)/fa20/hw/hw02/sales.csv