# Files distributed to students (.ok & tests/ handled automatically)
fa20/lab/lab01.d: $(MATERIALS_DST)/fa20/lab/lab01/error.jpg
fa20/lab/lab01.d: $(MATERIALS_DST)/fa20/lab/lab01/numberline_0.png
fa20/lab/lab01.d: $(MATERIALS_DST)/fa20/lab/lab01/numberline_1.png
fa20/lab/lab01.d: $(MATERIALS_DST)/fa20/lab/lab01/map.jpg