# Files distributed to students (.ok & tests/ handled automatically)
fa20/hw/hw10.d: $(MATERIALS_DST)/fa20/hw/hw10/pten.csv
fa20/hw/hw10.d: $(MATERIALS_DST)/fa20/hw/hw10/normal1.png
fa20/hw/hw10.d: $(MATERIALS_DST)/fa20/hw/hw10/normal2.png
fa20/hw/hw10.d: $(MATERIALS_DST)/fa20/hw/hw10/virus-log-chart.jpg