# Files distributed to students (.ok & tests/ handled automatically)
fa20/hw/hw04.d: $(MATERIALS_DST)/fa20/hw/hw04/burrito.csv
fa20/hw/hw04.d: $(MATERIALS_DST)/fa20/hw/hw04/burritos_types.csv
fa20/hw/hw04.d: $(MATERIALS_DST)/fa20/hw/hw04/ratings.csv
fa20/hw/hw04.d: $(MATERIALS_DST)/fa20/hw/hw04/faculty.csv
fa20/hw/hw04.d: $(MATERIALS_DST)/fa20/hw/hw04/berkeley_faculty.csv