# Files distributed to students (.ok & tests/ handled automatically)
fa20/project/project2.d: $(MATERIALS_DST)/fa20/project/project2/causes_of_death.csv
fa20/project/project2.d: $(MATERIALS_DST)/fa20/project/project2/serum_cholesterol.csv
fa20/project/project2.d: $(MATERIALS_DST)/fa20/project/project2/mortality_summary.csv
fa20/project/project2.d: $(MATERIALS_DST)/fa20/project/project2/framingham.csv
fa20/project/project2.d: $(MATERIALS_DST)/fa20/project/project2/bootstrap_rrs.csv
fa20/project/project2.d: $(MATERIALS_DST)/fa20/project/project2/bootstrap-HERS.png
fa20/project/project2.d: $(MATERIALS_DST)/fa20/project/project2/HERS-table.png
fa20/project/project2.d: $(MATERIALS_DST)/fa20/project/project2/NHS.csv
fa20/project/project2.d: $(MATERIALS_DST)/fa20/project/project2/hazardrate.png