# Files distributed to students (.ok & tests/ handled automatically)
fa20/vitamin/vitamin35.d: $(MATERIALS_DST)/fa20/vitamin/vitamin35/feedback.py
fa20/vitamin/vitamin35.d: $(MATERIALS_DST)/fa20/vitamin/vitamin35/classification.png