# Files distributed to students (.ok & tests/ handled automatically)
fa20/hw/hw06.d: $(MATERIALS_DST)/fa20/hw/hw06/player_data.csv
fa20/hw/hw06.d: $(MATERIALS_DST)/fa20/hw/hw06/salary_data.csv
fa20/hw/hw06.d: $(MATERIALS_DST)/fa20/hw/hw06/sample_salary_data.csv
fa20/hw/hw06.d: $(MATERIALS_DST)/fa20/hw/hw06/earthquakes_2019.csv