# Files distributed to students (.ok & tests/ handled automatically)
fa20/vitamin/vitamin06.d: $(MATERIALS_DST)/fa20/vitamin/vitamin06/census_tbl.png
fa20/vitamin/vitamin06.d: $(MATERIALS_DST)/fa20/vitamin/vitamin06/feedback.py