# Files distributed to students (.ok & tests/ handled automatically)
fa20/lab/lab04.d: $(MATERIALS_DST)/fa20/lab/lab04/raw_compensation.csv
fa20/lab/lab04.d: $(MATERIALS_DST)/fa20/lab/lab04/movies_by_year.csv
fa20/lab/lab04.d: $(MATERIALS_DST)/fa20/lab/lab04/apply.png