# Files distributed to students (.ok & tests/ handled automatically)
fa20/lab/lab05.d: $(MATERIALS_DST)/fa20/lab/lab05/Austen_PrideAndPrejudice.txt
fa20/lab/lab05.d: $(MATERIALS_DST)/fa20/lab/lab05/player_data.csv
fa20/lab/lab05.d: $(MATERIALS_DST)/fa20/lab/lab05/salary_data.csv
fa20/lab/lab05.d: $(MATERIALS_DST)/fa20/lab/lab05/small_srswor_salary.csv
fa20/lab/lab05.d: $(MATERIALS_DST)/fa20/lab/lab05/large_srswor_salary.csv
fa20/lab/lab05.d: $(MATERIALS_DST)/fa20/lab/lab05/comparisons.png
fa20/lab/lab05.d: $(MATERIALS_DST)/fa20/lab/lab05/nacho_reactions.png