# Files distributed to students (.ok & tests/ handled automatically)
fa20/lab/lab03.d: $(MATERIALS_DST)/fa20/lab/lab03/world_population.csv
fa20/lab/lab03.d: $(MATERIALS_DST)/fa20/lab/lab03/array_logarithm.jpg
fa20/lab/lab03.d: $(MATERIALS_DST)/fa20/lab/lab03/array_multiplication.jpg
fa20/lab/lab03.d: $(MATERIALS_DST)/fa20/lab/lab03/more_restaurant_bills.csv
fa20/lab/lab03.d: $(MATERIALS_DST)/fa20/lab/lab03/excel_array.jpg
fa20/lab/lab03.d: $(MATERIALS_DST)/fa20/lab/lab03/chaining_method_calls.png
fa20/lab/lab03.d: $(MATERIALS_DST)/fa20/lab/lab03/imdb.csv