# Files distributed to students (.ok & tests/ handled automatically)
fa20/vitamin/vitamin08.d: $(MATERIALS_DST)/fa20/vitamin/vitamin08/movie_hist.png
fa20/vitamin/vitamin08.d: $(MATERIALS_DST)/fa20/vitamin/vitamin08/feedback.py