# Files distributed to students (.ok & tests/ handled automatically)
fa20/project/project1.d: $(MATERIALS_DST)/fa20/project/project1/child_mortality.csv
fa20/project/project1.d: $(MATERIALS_DST)/fa20/project/project1/countries.csv
fa20/project/project1.d: $(MATERIALS_DST)/fa20/project/project1/fertility.csv
fa20/project/project1.d: $(MATERIALS_DST)/fa20/project/project1/life_expectancy.csv
fa20/project/project1.d: $(MATERIALS_DST)/fa20/project/project1/pew_population_projection.png
fa20/project/project1.d: $(MATERIALS_DST)/fa20/project/project1/population.csv
fa20/project/project1.d: $(MATERIALS_DST)/fa20/project/project1/poverty.csv